version: '3'
services:
  backend:
    image: maxi45/vartalaap:0.0.2.backend
    container_name: backend_container
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    image: maxi45/vartalaap:0.0.2.Frontend
    container_name: frontend_container
    ports:
      - "3000:80"
    depends_on:
      - backend

